CreateContact:
  handler: lambda/CreateContact/index.handler
  description: "POST /contacts/:userId"
  memorySize: 512
  timeout: 15
  events:
    - httpApi:
        path: /contacts/{userId}
        method: post
#  environment:
#    CACHE_EXPIRY_MS: ${file(./config/config.${self:provider.stage}.json):CACHE_EXPIRY_MS}
  iamRoleStatementsInherit: true
  iamRoleStatements: []
#  - Effect: Allow
#    Action:
#    - s3:putObject
#    - s3:putObjectTagging
#    Resource:
#      Fn::Join:
#      - "/"
#      - - Fn::GetAtt: [SpaceUnavailabilitiesBookingsBucket, Arn]
